### ISSUE TITLE
Database: design User table

### ISSUE THREAD

**Issue by zhouhao** [Ellychou/Java-Web-blog#1]
Create use table in database
1. Define as more fields as you can
2. Define the primary key
[3. Know something about MD5(encryption), then you will know the length of password] ---- This is a general way to store password encrypted in database
4. more...

**Comment by zhouhao** [comment]
After you designed database, please include your design as XXX.sql into your project

**Comment by Ellychou** [comment]
Design a user table with these fields: UserID, userName, email, password,last_login,data_created
